// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYe5dFVmXiHJjjAz9FVKq-ZAeC6K4yvIo',
    appId: '1:982021563960:web:e64e2053613b366b3328cd',
    messagingSenderId: '982021563960',
    projectId: 'fittracker-1da45',
    authDomain: 'fittracker-1da45.firebaseapp.com',
    storageBucket: 'fittracker-1da45.firebasestorage.app',
    measurementId: 'G-LLP7M318GT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGtzc-66mytx0ynyqAJtGky6Cebhd1zVY',
    appId: '1:982021563960:android:469c7fbb1b78000f3328cd',
    messagingSenderId: '982021563960',
    projectId: 'fittracker-1da45',
    storageBucket: 'fittracker-1da45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXft0xiJPW1yivRjj_1uHRqpqt1vWsuA',
    appId: '1:982021563960:ios:7467004d7d99abab3328cd',
    messagingSenderId: '982021563960',
    projectId: 'fittracker-1da45',
    storageBucket: 'fittracker-1da45.firebasestorage.app',
    androidClientId: '982021563960-jfvpmv0vp8m0q3jdpqjcgcdn50nno1po.apps.googleusercontent.com',
    iosClientId: '982021563960-6l7n98vee62t87f6n5qat13dr9ckq2e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittrackr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFXft0xiJPW1yivRjj_1uHRqpqt1vWsuA',
    appId: '1:982021563960:ios:7467004d7d99abab3328cd',
    messagingSenderId: '982021563960',
    projectId: 'fittracker-1da45',
    storageBucket: 'fittracker-1da45.firebasestorage.app',
    androidClientId: '982021563960-jfvpmv0vp8m0q3jdpqjcgcdn50nno1po.apps.googleusercontent.com',
    iosClientId: '982021563960-6l7n98vee62t87f6n5qat13dr9ckq2e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fittrackr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYe5dFVmXiHJjjAz9FVKq-ZAeC6K4yvIo',
    appId: '1:982021563960:web:5afe9b27d504585f3328cd',
    messagingSenderId: '982021563960',
    projectId: 'fittracker-1da45',
    authDomain: 'fittracker-1da45.firebaseapp.com',
    storageBucket: 'fittracker-1da45.firebasestorage.app',
    measurementId: 'G-1Z8RW7PVQC',
  );

}